### PR TITLE
Improved accessibility

### PR DESCRIPTION
**Pull request by OpenSourceSimon**

### CODE REVIEW

**Comment by LevaniVashadze** [comment]
image
using firefox for detecting issues is great

**Comment by LevaniVashadze** [comment]
@OpenSourceSimon whats left to do for this PR to be merged

**Comment by OpenSourceSimon** [comment]
> @OpenSourceSimon whats left to do for this PR to be merged

Nothing less than merge conflicts

**Comment by OpenSourceSimon** [comment]
I'll do this again a later time. There are so much changes that merging the conflicts will take longer than searching for new improvements.

**Pull request closed without merging**
