### PR TITLE
Update about.html

### PR DESCRIPTION
**Pull request by ExplodeC0de**

### CODE REVIEW

**Comment by LevaniVashadze** [comment]
Please change to the development branch

**Comment by LevaniVashadze** [comment]
I updated the base branch and transformed this PR into a draft

**Comment by ExplodeC0de** [comment]
ok

**Comment by ImmaHarry** [comment]
Closing this PR since @ExplodeC0de on Discord confirmed that he won't be able to work anymore on this due to some personal problems and stuff. Thank you for taking time for this though 🤍🤍!

**Pull request closed without merging**
