### PR TITLE
Added more (tech) news outlets

### PR DESCRIPTION
**Pull request by CattopyTheWeb**
I have added more (tech) news outlets - Kaspersky Blog, Bleeping Computer, Dark Reading, The Hacker News and the Avast blog.

### CODE REVIEW

**Comment by CattopyTheWeb** [comment]
Uh so now what?

**Comment by ImmaHarry** [comment]
Hey @CattopyTheWeb! Thank you for your contribution. We appreciate you adding new sources, but we don't require them since:
1. We already have enough.
2. We are now focussing on the blogging system.
3. We would have to overhaul our entire register section which we are not willing to since we have already closed that page, for now at the very least.

Looking forward to more contributions from you! Cheers 🍻🍻

**Comment by LevaniVashadze** [comment]
We will keep this PR in mind and reopen it if we change our mind

**Comment by LevaniVashadze** [comment]
Hey one of our news sources failed us so we are back and reopening this PR

**Comment by LevaniVashadze** [comment]
I removed most of the sources because of: 
1. Avast and Kaspersky are antivirus companies
2. Dark Reader news isn't tech related
3. Bleeping computer and Hacker news are okay, but we have better options

**Pull request merged**
